### ISSUE TITLE
Sensor decimal inconsistency

### ISSUE THREAD

**Issue by carlhye** [nic6911/Wavin-Sentio#2]
The Wavin sensors report temperature with one decimal point on the wall mounted unit.
In Home Assistant this decimal reporting is not consistant - one place in the ESP integration, it shows with one decimal, another it shows zero decimals.

The control entity in HA seems to show one decimal for the sensor reading, Current Temperature: 22,5 in this example.
<img width="591" alt="image" src="https://github.com/nic6911/Wavin-Sentio/assets/82280057/19754a16-a1ea-47b9-afe5-bcea83d99ee3">

The sensor entity for the same unit, show zero decimals, rounding 22,5 up to 23).
<img width="589" alt="image" src="https://github.com/nic6911/Wavin-Sentio/assets/82280057/f2f8dd0c-7222-4b88-acd6-8489318bb2de">

The expected behaviour would be to have everything with one decimal, across all sensors, as it's also shown with one decimal on the wall mounted Wavin sensor unit.

**Comment by nic6911** [comment]
fixed

**Comment by carlhye** [comment]
That's great!

Thank you for looking at this.

I'm rather new to this - how do I go about updating the device? 
Just replace the .yaml or... ?

**Comment by nic6911** [comment]
Just upload the code again from esphome.It should pull the required libraries.Best regards, MogensDen 7. nov. 2023 kl. 10.11 skrev carlhye ***@***.***>:﻿
That's great!
Thank you for looking at this.
I'm rather new to this - how do I go about updating the device?
Just replace the .yaml or... ?
